shopen; Refactoring - fixed if statements and varaible names
I fixed the variable names to not conflict with the actual file variable
name. I also fixed the if statements that are searching for a
specific desktop file, because previously the comparaisons would
always fail due to matching the whole path. I fixed this by using
the shell substring removal.

diff --git a/shopen b/shopen
--- a/shopen
+++ b/shopen
@@ -14,72 +14,82 @@ do
 		WANTDESKTOPFILE=$(grep $MIME_TYPE $MIMEAPPSLIST | cut -d'=' -f2)
 		echo "Want: $WANTDESKTOPFILE"
 	fi
-	# Look in USER_DESKTOP_FILES_DIR first
+ # Look in USER_DESKTOP_FILES_DIR first
 
 	FOUNDDESKTOP=N
-	for f in $USER_DESKTOP_FILES_DIR*
+	for deskf in $USER_DESKTOP_FILES_DIR*
 	do
 		# if we found the desktop file, save the location
 		# and break the loop
-		#if echo $f | grep -q $WANTDESKTOPFILE
-		if [ "$f" = "$WANTDESKTOPFILE" ]
+		#if echo $deskf | grep -q $WANTDESKTOPFILE
+		if [ "${deskf##*/}" = "$WANTDESKTOPFILE" ]
 		then
-			echo $f
+			echo $deskf
 			FOUNDDESKTOP=Y
-			DESKTOPFILE="$(echo $f | grep "$WANTDESKTOPFILE")"
+			DESKTOPFILE="$(echo $deskf | grep "$WANTDESKTOPFILE")"
 			break
 		fi
 	done
 
-	# Now look into SYSTEM_DESKTOP_FILES_DIR
+ # Now look into SYSTEM_DESKTOP_FILES_DIR
 
-	# Only search if we didn't find it in the users desktop file
-	# directory
+ # Only search if we didn't find it in the users desktop file
+ # directory
 
 	[ $FOUNDDESKTOP = N ] && {
-		for f in $SYSTEM_DESKTOP_FILES_DIR*
+		for deskf in $SYSTEM_DESKTOP_FILES_DIR*
 		do
-			#if echo $f | grep -q $WANTDESKTOPFILE
-			if [ "$f" = "$WANTDESKTOPFILE" ]
+			#if echo $deskf | grep -q $WANTDESKTOPFILE
+			if [ "${deskf##*/}" = "$WANTDESKTOPFILE" ]
 			then
-				echo $f
+				echo $deskf
 				FOUNDDESKTOP=Y
-				DESKTOPFILE="$(echo $f | grep "$WANTDESKTOPFILE")"
+				DESKTOPFILE="$(echo $deskf | grep "$WANTDESKTOPFILE")"
 				break
 			fi
 		done
 	}
 
-	# if we still havent found the proper desktop file, we now need to search for
-	# a desktop file that can handle the proper mimetype
+ # if we still havent found the proper desktop file, we now need to search for
+ # a desktop file that can handle the proper mimetype
 
-	# First check the user directory
+ # First check the user directory
 	[ $FOUNDDESKTOP = N ] && {
-		for f in $USER_DESKTOP_FILES_DIR*
+		for deskf in $USER_DESKTOP_FILES_DIR*
 		do
-			if grep -q $MIME_TYPE $f
+			if grep -q $MIME_TYPE $deskf
 			then
-				echo $f
+				echo $deskf
 				FOUNDDESKTOP=Y
-				DESKTOPFILE=$f
+				DESKTOPFILE=$deskf
 				break
 			fi
 		done
 	}
 
-	# now check the system directory
+ # now check the system directory
 	[ $FOUNDDESKTOP = N ] && {
-		for f in $SYSTEM_DESKTOP_FILES_DIR*
+		for deskf in $SYSTEM_DESKTOP_FILES_DIR*
 		do
-			if grep -q "$MIME_TYPE" $f
+			if grep -q "$MIME_TYPE" $deskf
 			then
-				echo $f
+				echo $deskf
 				FOUNDDESKTOP=Y
-				DESKTOPFILE=$f
+				DESKTOPFILE=$deskf
 				break
 			fi
 		done
 	}
+
+	# if DESKTOPFILE is empty, then we should exit with a 1
+	# because at this point we have found no desktop file
+	# to handle our mimetype
+	[ "$DESKTOPFILE" = "" ] && echo "failure" && exit 1
+
+	# Now we open up the file according to how the desktop
+	# file specifies
+
+	echo $f
 
 	echo $DESKTOPFILE
 
